title: NCAR Dog Protocols
description: Dog handling protocols for staff and volunteers
baseurl: "/ncar-information"
url: ""

# Build settings
markdown: kramdown
permalink: /:title/

# Exclude from processing
exclude:
  - src/
  - _scripts/
  - README.md
  - Gemfile
  - Gemfile.lock
