title: NCAR Dog Protocols
description: Dog handling protocols for staff and volunteers
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Exclude from processing
exclude:
  - src/
  - README.md
  - Gemfile
  - Gemfile.lock
